apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mymongologdb
spec:
  serviceName: mymongologdb-service
  replicas: 1
  selector:
    matchLabels:
      app: mymongologdb
  template:
    metadata:
      labels:
        app: mymongologdb
    spec:
      containers:
        - name: mymongologdb
          image: mongo:3
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mymongologdb_data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: MONGO_PASSWORD
      envFrom:
        - configMapRef:
            name: mongo-config.properties
  volumeClaimTemplates:
    - metadata:
        name: mymongologdb_data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mymongologdb-service
spec:
  selector:
    app: mymongologdb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
      nodePort: 30000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_CONTAINER: mymongologdb
  MONGO_HOST: mymongologdb
  MONGO_PORT: 27018
  MONGO_DB: dblogger
  MONGO_USERNAME: user
  MONGO_PASSWORD: pass
  MONGO_AUTHUSER: admin





