apiVersion: apps/v1
kind: Deployment
metadata:
  name: epa-inventory-app-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      role: epa-inventory-app-logger
  template:
    metadata:
      labels:
        role: epa-inventory-app-logger
    spec:
      containers:
        - name: epa-inventory-app-logger
          image: cerjionava/epa_inventory_app_logger:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-log-config

---

apiVersion: v1
kind: Service
metadata:
  name: epa-inventory-app-logger-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    role: epa-inventory-app-logger

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-log-config
data:
  APP_PORT: '8081'
  MONGO_CONTAINER: mongodblog
  MONGO_HOST: mongodblog-service
  MONGO_PORT: '27018'
  MONGO_DB: dblogger
  MONGO_USERNAME: user
  MONGO_PASSWORD: pass
  MONGO_AUTHUSER: admin
  RABBIT_CONTAINER: myrabbitmq
  RABBIT_HOST: myrabbitmq-service
  RABBIT_USERNAME: guest
  RABBIT_PASSWORD: guest
  RABBIT_PORT: '5672'
  RABBIT_GUI_PORT: '15672'
  RABBIT_URI: amqp://guest:guest@myrabbitmq-service:5672
  QUEUE_SALE_ERROR: queue-sale-error
  QUEUE_SALE_LOGS: queue-sale-logs
  EXCHANGE_SALE: exchange-sale
  ROUTING_KEY_SALE_ERROR: sale.routing.error
  ROUTING_KEY_SALE_LOGS: sale.routing.logs
  QUEUE_INVENTORY_ERROR: queue-inventory-error
  QUEUE_INVENTORY_LOGS: queue-inventory-logs
  EXCHANGE_INVENTORY: exchange-inventory
  ROUTING_KEY_INVENTORY_ERROR: inventory.routing.error
  ROUTING_KEY_INVENTORY_LOGS: inventory.routing.logs





