apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodblog-statefulset
spec:
  serviceName: mongodblog-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodblog
  template:
    metadata:
      labels:
        app: mongodblog
    spec:
      containers:
        - name: mongodblog
          image: mongo:3
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodblog-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass
  volumeClaimTemplates:
    - metadata:
        name: mongodblog-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodblog-service
spec:
  selector:
    app: mongodblog
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001