version: "3.9"

services:
  applogger:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    links:
      - mymongologdb
      - myrabbitmq
    env_file:
      - .env
    networks:
      - default

  mymongologdb:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mymongologdb_data:/data/db
    networks:
      - default

  myrabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBIT_CONTAINER}
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${RABBIT_GUI_PORT}:${RABBIT_GUI_PORT}"
    networks:
      - default

volumes:
  mymongologdb_data: {}

networks:
  default:
    name: epa_inventory_app_default
    external: true
